repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-yaml
        args: [--allow-multiple-documents]
